export const KEY_REDUCER = 'SPOT_LIGHT';
export const INIT = `${KEY_REDUCER}/INIT`;

export const FETCH_SPOT_BY_ID = `${KEY_REDUCER}/FETCH_SPOT_BY_ID`;
export const SET_SPOT_LOADING = `${KEY_REDUCER}/SET_SPOT_LOADING`;
export const SET_SPOT_DONE = `${KEY_REDUCER}/SET_SPOT_DONE`;
